### ISSUE TITLE
Wie genau funktioniert das?

### ISSUE THREAD

**Issue by optimusl77** [azxnexception/ColorPickerHTML#1]
Hast du Discord, ich würde mich interessieren wie genau das aufgebaut ist.

**Comment by kotlinplugin** [comment]
Es ist eine simple Website, einfach Index öffnen, und sie ist gestartet. Ich gebe meinen Discord nicht einfach so raus, entschuldige!

**Comment by optimusl77** [comment]
Gibt es eine andere Möglichkeit, dich zu kontaktieren? Ich finde viele deiner Projekte spannend und hätte einige fragen dazu.
